# Generated by Django 4.0.4 on 2022-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JABATAN', models.CharField(choices=[('JKA', 'JABATAN KEJURUTERAAN AWAM'), ('JKE', 'JABATAN KEJURUTERAAN ELEKTRIK'), ('JKM', 'JABATAN KEJURUTERAAN MEKANIKAL'), ('JP', 'JABATAN PERDAGANGAN'), ('JTMK', 'JABATAN TEKNOLOGI MAKLUMAT DAN KOMPUTER'), ('JKPK', 'JABATAN KEJURUTERAAN PETROKIMIA'), ('JPA', 'JABATAN PENGAJIAN AM'), ('JMSK', 'JABATAN MATEMATIK, SAINS DAN KOMPUTER')], max_length=200)),
                ('Penyelaras', models.CharField(max_length=200)),
                ('Ketua_Jabatan', models.CharField(max_length=200)),
                ('Tempoh', models.CharField(choices=[('1st_half', 'Sesi Jan - Jun'), ('2nd_half', 'Sesi Jul - Ogos')], max_length=200)),
                ('tahun', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=200)),
                ('KPI', models.CharField(choices=[('KPI 1', 'KPI 1: Taklimat OBE kepada pelajar baharu & pensyarah kursus mengikut keperluan manual ETAC dan Garis Panduan Amalan Baik MQA'), ('KPI 2', 'KPI 2: Taklimat dan memastikan pensyarah kursus memahami rekabentuk kurikulum'), ('KPI 3', 'KPI 3: Taklimat  merancang penilaian dengan mengikut keperluan kurikulum'), ('KPI 4', 'KPI 4: Taklimat  membaca laporan CORR dan penghasilan CQI')], max_length=200)),
                ('Tajuk_Aktiviti', models.CharField(max_length=200)),
                ('Tarikh_Aktiviti', models.DateField()),
                ('Objektif_Aktiviti', models.TextField(max_length=1000)),
                ('Catatan', models.TextField(max_length=1000)),
            ],
        ),
    ]
