# Generated by Django 4.0.4 on 2022-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputformmodel',
            name='Ketua_Jabatan',
        ),
        migrations.RemoveField(
            model_name='inputformmodel',
            name='Penyelaras',
        ),
        migrations.AlterField(
            model_name='inputformmodel',
            name='JABATAN',
            field=models.CharField(choices=[('JABATAN KEJURUTERAAN AWAM', 'JABATAN KEJURUTERAAN AWAM'), ('JABATAN KEJURUTERAAN ELEKTRIK', 'JABATAN KEJURUTERAAN ELEKTRIK'), ('JABATAN KEJURUTERAAN MEKANIKAL', 'JABATAN KEJURUTERAAN MEKANIKAL'), ('JABATAN PERDAGANGAN', 'JABATAN PERDAGANGAN'), ('JABATAN TEKNOLOGI MAKLUMAT DAN KOMPUTER', 'JABATAN TEKNOLOGI MAKLUMAT DAN KOMPUTER'), ('JABATAN KEJURUTERAAN PETROKIMIA', 'JABATAN KEJURUTERAAN PETROKIMIA'), ('JABATAN PENGAJIAN AM', 'JABATAN PENGAJIAN AM'), ('JABATAN MATEMATIK, SAINS DAN KOMPUTER', 'JABATAN MATEMATIK, SAINS DAN KOMPUTER')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputformmodel',
            name='Tempoh',
            field=models.CharField(choices=[('JAN - JUL', 'Sesi Jan - Jun'), ('JUL - OGOS', 'Sesi Jul - Ogos')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputformmodel',
            name='tahun',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=200),
        ),
    ]
